### ISSUE TITLE
False detection of goPaint installation on load

### ISSUE THREAD

**Issue by Feniksovich** [OneLiteFeatherNET/BetterGoPaint#6]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

BetterGoPaint falsely detects that goPaint installed and then disables itself. Since commit https://github.com/OneLiteFeatherNET/BetterGoPaint/commit/b6542ab053c9fc821bcd18349e92a7150b4b837f.
I guess it's related to the following change: 
https://github.com/OneLiteFeatherNET/BetterGoPaint/blob/b6542ab053c9fc821bcd18349e92a7150b4b837f/build.gradle.kts#L108

### To Reproduce

1. Install BGP that includes mentoined commit (e.g. [latest](https://hangar.papermc.io/TheMeinerLP/BetterGoPaint/versions/1.0.0-SNAPSHOT+85fd9f3) at the moment)
2. Make sure you don't have `goPaint` plugin installed at the same time.
3. Run the server and got disabled plugin.

### Expected behaviour

BGP should load normally.

### goPaint Version

1.0.0-SNAPSHOT+85fd9f3

### Checklist

- [X] I am using the newest build from https://github.com/TheMeinerLP/BetterGoPaint and the issue still persists.

**Comment by Voxelpioneer** [comment]
I'm having this same issue

**Comment by TheMeinerLP** [comment]
Thanks for reporting, I look today at that issue
